### ISSUE TITLE
Add a wrapper script in the bin directory to make it easier to run extract_msg

### ISSUE THREAD

**Issue by zeroepoch** [TeamMsgExtractor/msg-extractor#162]
**Bug Metadata**
* Version of extract_msg: 0.27.8
* Your python version: Python 3.9.0
* How did you launch extract_msg?
  - `python3 -m extract_msg`

**Describe the bug**
The pip package doesn't install a script in the bin directory (or maybe it doesn't happen on python 3.9 or Fedora for some reason). I have to use `python3 -m extract_msg ...` in order to run the main script. It would be nice if when installing the wheel file via pip that a wrapper script was installed in the normal bin directory to make it easier to launch. `~/.local/bin` is normally added to your `PATH` for example.

**Comment by TheElementalOfDestruction** [comment]
TBH, this isn't a bug: we just never implemented it. I don't actually know how to do that yet, so I guess I have something to look into,

**Comment by TheElementalOfDestruction** [comment]
This should work now. The script is simply called "extract_msg". Let me know if you have any problems.

**Comment by zeroepoch** [comment]
Maybe this is a Windows vs Linux thing, but the script was not executable when installed, so I had to do `chmod +x extract_msg`. Also it has DOS line endings so it printed the error:
```
/usr/bin/env: ‘python\r’: No such file or directory
```
After fixing the executable permissions and line endings it appears to work. Also the stdout option worked great.

**Comment by TheElementalOfDestruction** [comment]
This should now be fully working. I tested it myself (or tried to), but can you confirm as well?

**Comment by zeroepoch** [comment]
I'm still seeing the same behavior as before. Although when I clone the repo and build the wheel file myself it works fine. I see as part of `python3 setup.py bdist_wheel` it's setting the permissions to 755. Also if I use `setup.py` to install directly without a wheel file setuptools generates it's own bin script and that works as well. I wonder if the issue is the wheel files are being created on a Windows system (where executable permissions don't matter) and not a Unix based system, such as Linux or MacOS?

**Comment by TheElementalOfDestruction** [comment]
The weird thing is I tried it myself on one of my systems and it worked, but I might have installed it directly from git rather than pypi and that might be why. I did use chmod on my windows system and set it to executable, but it doesn't seem to have fixed the problem.

I don't currently have a fully formed Linux install that I can use for uploading to pypi right now.

**Comment by zeroepoch** [comment]
You could try using WSL (and Windows Terminal) if you want a quick Linux setup on Windows. I believe that should be sufficient to create a Linux compatible wheel file. I assume Python on Windows can handle either line endings. The problem on Linux is the `#!...` line at the top is read by the shell not Python.

**Comment by TheElementalOfDestruction** [comment]
I think I fixed the problem, but let me know if it still persists.

**Comment by staticaland** [comment]
It is normally done through `pip` by adding something like this to `setup.py`:

```
entry_points={
    'console_scripts': [
        'extract_msg = extract_msg.main:main',
    ]
```

See https://packaging.python.org/specifications/entry-points/

**Comment by TheElementalOfDestruction** [comment]
Thanks to @staticaland I figured out how to do this (I think). Based on some tests that I did, this should now be completely fixed in 0.28.0

**Comment by zeroepoch** [comment]
Thanks @TheElementalOfDestruction! It's working as expected now. I see you were also able to remove the wrapper script as well which is nice.
