### ISSUE TITLE
NameError in utils.py

### ISSUE THREAD

**Issue by StephenGrey** [TeamMsgExtractor/msg-extractor#177]
In order to get your bug addressed in a timely manner, or at all :smiley:, please fill out the below bug report. Please try to make it as easy as possible for us to understand what is going on. We may close out any bugs or issues without warning that are not complete or coherent.

In the bug template below anything is [square brackets] should be filled out or removed if the item doesn't apply.

Should you encounter an error that has not already been reported, please do the following when reporting it:
**Bug Metadata**
* Version of extract_msg: [0.27.14)]
* Your python version: Python [3.7.0]
* How did you launch extract_msg?
  - [ ] My command line or
  - [X ] I used the extract_msg package

**Describe the bug**
Missing import / possible compatibility issue.
A missing piece of meta is throwing an error which is triggers an exception that fails on copy.deepcopy
retrurning a NameError

[ If applicable ]
**What code did you use or can we use to reproduce this error?

The problem may be evident to you from the traceback.
I've imported msg_extract from pip

```
in Python, import msg_extract
extract_msg.Message(path) throws the error.
```
I note you have recently edited utils.py

Is there a message.msg file you want to share to help us reproduce this?
- [ ] Uploaded message (drag and drop on this window)
- [ ] Emailed message as an attachment to admins: [Enter Subject Line Here]
Happy to send one if required, although will require some editing.

**Traceback**
```
Traceback (most recent call last):
  File "C:\Users\User\env\lib\site-packages\extract_msg\msg.py", line 422, in named
    return self.__namedProperties
AttributeError: 'Message' object has no attribute '_MSGFile__namedProperties'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\User\env\lib\site-packages\extract_msg\message.py", line 28, in __init__
    MessageBase.__init__(self, path, prefix, attachmentClass, filename, delayAttachments, overrideEncoding)
  File "C:\Users\User\env\lib\site-packages\extract_msg\message_base.py", line 61, in __init__
    self.named
  File "C:\Users\User\env\lib\site-packages\extract_msg\msg.py", line 424, in named
    self.__namedProperties = Named(self)
  File "C:\Users\User\env\lib\site-packages\extract_msg\named.py", line 63, in __init__
    self.__properties.append(StringNamedProperty(entry, names[entry['id']], msg._getTypedData(streamID)) if entry['pkind'] == constants.STRING_NAMED else NumericalNamedProperty(entry, msg._getTypedData(streamID)))
  File "C:\Users\User\env\lib\site-packages\extract_msg\msg.py", line 177, in _getTypedData
    found, result = self._getTypedStream('__substg1.0_' + id, prefix, _type)
  File "C:\Users\User\env\lib\site-packages\extract_msg\msg.py", line 255, in _getTypedStream
    return True, parseType(int(_type, 16), contents, self.stringEncoding, extras)
  File "C:\Users\User\env\lib\site-packages\extract_msg\utils.py", line 458, in parseType
    ret = copy.deepcopy(extras)
NameError: name 'copy' is not defined
```

**Screenshots**
[Insert any screenshots or debug pictures here]

**Additional context**
[Add any other context about the problem here.]

**Comment by TheElementalOfDestruction** [comment]
This should now be fixed. Please let us know.

**Comment by StephenGrey** [comment]
Thanks for looking at it - will update and check.

**Comment by TheElementalOfDestruction** [comment]
That's weird that I did that. I know exactly what the problem is, but that may take me a little bit to correct. I have to figure out what I was actually trying to put.

**Comment by TheElementalOfDestruction** [comment]
@StephenGrey Would you mind running this code (replacing `MESSAGE_PATH` with the path to your message file) and posting the results here?
```python
import extract_msg
import extract_msg.utils
from extract_msg import constants

import logging
import sys

root = logging.getLogger()
root.setLevel(logging.DEBUG)

handler = logging.StreamHandler(sys.stdout)
handler.setLevel(logging.DEBUG)
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
handler.setFormatter(formatter)
root.addHandler(handler)

class Message(extract_msg.Message):
    def _getTypedStream(self, filename, prefix = True, _type = None):
        """
        Override function. This should work.
        """
        extract_msg.utils.verifyType(_type)
        filename = self.fix_path(filename, prefix)
        for x in (filename + _type,) if _type is not None else self.slistDir():
            if x.startswith(filename) and x.find('-') == -1:
                contents = self._getStream(x, False)
                if len(contents) == 0:
                    return True, None # We found the file, but it was empty.
                extras = []
                _type = x[-4:]
                if x[-4] == '1': # It's a multiple
                    if _type in ('101F', '101E'):
                        streams = len(contents) // 4 # These lengths are normal.
                    elif _type == '1102':
                        streams = len(contents) // 8 # These lengths have 4 0x00 bytes at the end for seemingly no reason. They are "reserved" bytes
                    elif _type in ('1002', '1003', '1004', '1005', '1007', '1014', '1040', '1048'):
                        try:
                            streams = self.mainProperties[x[-8:]].realLength
                        except:
                            root.error('Could not find matching VariableLengthProp for stream {}'.format(x))
                            streams = len(contents) // (2 if _type in constants.MULTIPLE_2_BYTES else 4 if _type in constants.MULTIPLE_4_BYTES else 8 if _type in constants.MULTIPLE_8_BYTES else 16)
                    else:
                        raise NotImplementedError('The stream specified is of type {}. We don\'t currently understand exactly how this type works. If it is mandatory that you have the contents of this stream, please create an issue labled "NotImplementedError: _getTypedStream {}".'.format(_type, _type))
                    if _type in ('101F', '101E', '1102'):
                        if self.Exists(x + '-00000000', False):
                            for y in range(streams):
                                if self.Exists(x + '-' + extract_msg.utils.properHex(y, 8), False):
                                    extras.append(self._getStream(x + '-' + extract_msg.utils.properHex(y, 8), False))
                    elif _type in ('1002', '1003', '1004', '1005', '1007', '1014', '1040', '1048'):
                        extras = extract_msg.utils.divide(contents, (2 if _type in constants.MULTIPLE_2_BYTES else 4 if _type in constants.MULTIPLE_4_BYTES else 8 if _type in constants.MULTIPLE_8_BYTES else 16))
                        contents = streams
                if _type == '1102':
                    root.debug(_type)
                    root.debug(contents)
                    #root.debug(extras) # I commented this out because the extras might contain sensitive data. If you don't care, you can uncomment this line
                return True, extract_msg.utils.parseType(int(_type, 16), contents, self.stringEncoding, extras)
        return False, None # We didn't find the stream.

msg = Message(MESSAGE_PATH)
```

**Comment by StephenGrey** [comment]
Sure. Will do.

**Comment by StephenGrey** [comment]
>>> try_temp.Message(path)
2021-01-06 14:19:37,273 - extract_msg.prop - ERROR - [Errno 22] Invalid argument
Traceback (most recent call last):
  File "C:\Users\User\env\lib\site-packages\extract_msg\msg.py", line 410, in mainProperties
    return self._prop
AttributeError: 'Message' object has no attribute '_prop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\env\lib\site-packages\extract_msg\prop.py", line 138, in parseType
    value = fromTimeStamp(msgEpoch(constants.ST3.unpack(value)[0]))
  File "C:\Users\User\env\lib\site-packages\extract_msg\utils.py", line 147, in fromTimeStamp
    return datetime.datetime.fromtimestamp(stamp, tzlocal.get_localzone())
OSError: [Errno 22] Invalid argument
2021-01-06 14:19:37,273 - extract_msg.prop - ERROR - [Errno 22] Invalid argument
Traceback (most recent call last):
  File "C:\Users\User\env\lib\site-packages\extract_msg\msg.py", line 410, in mainProperties
    return self._prop
AttributeError: 'Message' object has no attribute '_prop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\env\lib\site-packages\extract_msg\prop.py", line 138, in parseType
    value = fromTimeStamp(msgEpoch(constants.ST3.unpack(value)[0]))
  File "C:\Users\User\env\lib\site-packages\extract_msg\utils.py", line 147, in fromTimeStamp
    return datetime.datetime.fromtimestamp(stamp, tzlocal.get_localzone())
OSError: [Errno 22] Invalid argument
2021-01-06 14:19:37,275 - extract_msg.prop - ERROR - Timestamp value of {} caused an exception. This was probably caused by the time stamp being too far in the future.
2021-01-06 14:19:37,275 - extract_msg.prop - ERROR - Timestamp value of {} caused an exception. This was probably caused by the time stamp being too far in the future.
2021-01-06 14:19:37,276 - extract_msg.prop - ERROR - b'@\x00,\x80\x06\x00\x00\x00\x00@\xdd\xa3WE\xb3\x0c'
2021-01-06 14:19:37,276 - extract_msg.prop - ERROR - b'@\x00,\x80\x06\x00\x00\x00\x00@\xdd\xa3WE\xb3\x0c'
2021-01-06 14:19:37,294 - root - DEBUG - 1102
2021-01-06 14:19:37,294 - root - DEBUG - 1102
2021-01-06 14:19:37,294 - root - DEBUG - b'\x00\x00\x00\x00\x00\x00\x00\x00'
2021-01-06 14:19:37,294 - root - DEBUG - b'\x00\x00\x00\x00\x00\x00\x00\x00'
Traceback (most recent call last):
  File "C:\Users\User\env\lib\site-packages\extract_msg\msg.py", line 422, in named
    return self.__namedProperties
AttributeError: 'Message' object has no attribute '_MSGFile__namedProperties'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\User\env\lib\site-packages\extract_msg\message.py", line 28, in __init__
    MessageBase.__init__(self, path, prefix, attachmentClass, filename, delayAttachments, overrideEncoding)
  File "C:\Users\User\env\lib\site-packages\extract_msg\message_base.py", line 61, in __init__
    self.named
  File "C:\Users\User\env\lib\site-packages\extract_msg\msg.py", line 424, in named
    self.__namedProperties = Named(self)
  File "C:\Users\User\env\lib\site-packages\extract_msg\named.py", line 63, in __init__
    self.__properties.append(StringNamedProperty(entry, names[entry['id']], msg._getTypedData(streamID)) if entry['pkind'] == constants.STRING_NAMED else NumericalNamedProperty(entry, msg._getTypedData(streamID)))
  File "C:\Users\User\env\lib\site-packages\extract_msg\msg.py", line 177, in _getTypedData
    found, result = self._getTypedStream('__substg1.0_' + id, prefix, _type)
  File "C:\Users\User\Documents\GitHub\sleuth\wwwsearch\parse_email\try_temp.py", line 56, in _getTypedStream
    return True, extract_msg.utils.parseType(int(_type, 16), contents, self.stringEncoding, extras)
  File "C:\Users\User\env\lib\site-packages\extract_msg\utils.py", line 459, in parseType
    lengths = tuple(struct.unpack('<i', stream[pos*8:(pos+1)*8]) for pos in range(len(stream) // 8))
  File "C:\Users\User\env\lib\site-packages\extract_msg\utils.py", line 459, in <genexpr>
    lengths = tuple(struct.unpack('<i', stream[pos*8:(pos+1)*8]) for pos in range(len(stream) // 8))
struct.error: unpack requires a buffer of 4 bytes
>>> try_temp.Message(path)
2021-01-06 14:20:08,170 - extract_msg.prop - ERROR - [Errno 22] Invalid argument
Traceback (most recent call last):
  File "C:\Users\User\env\lib\site-packages\extract_msg\msg.py", line 410, in mainProperties
    return self._prop
AttributeError: 'Message' object has no attribute '_prop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\env\lib\site-packages\extract_msg\prop.py", line 138, in parseType
    value = fromTimeStamp(msgEpoch(constants.ST3.unpack(value)[0]))
  File "C:\Users\User\env\lib\site-packages\extract_msg\utils.py", line 147, in fromTimeStamp
    return datetime.datetime.fromtimestamp(stamp, tzlocal.get_localzone())
OSError: [Errno 22] Invalid argument
2021-01-06 14:20:08,170 - extract_msg.prop - ERROR - [Errno 22] Invalid argument
Traceback (most recent call last):
  File "C:\Users\User\env\lib\site-packages\extract_msg\msg.py", line 410, in mainProperties
    return self._prop
AttributeError: 'Message' object has no attribute '_prop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\env\lib\site-packages\extract_msg\prop.py", line 138, in parseType
    value = fromTimeStamp(msgEpoch(constants.ST3.unpack(value)[0]))
  File "C:\Users\User\env\lib\site-packages\extract_msg\utils.py", line 147, in fromTimeStamp
    return datetime.datetime.fromtimestamp(stamp, tzlocal.get_localzone())
OSError: [Errno 22] Invalid argument
2021-01-06 14:20:08,172 - extract_msg.prop - ERROR - Timestamp value of {} caused an exception. This was probably caused by the time stamp being too far in the future.
2021-01-06 14:20:08,172 - extract_msg.prop - ERROR - Timestamp value of {} caused an exception. This was probably caused by the time stamp being too far in the future.
2021-01-06 14:20:08,174 - extract_msg.prop - ERROR - b'@\x00,\x80\x06\x00\x00\x00\x00@\xdd\xa3WE\xb3\x0c'
2021-01-06 14:20:08,174 - extract_msg.prop - ERROR - b'@\x00,\x80\x06\x00\x00\x00\x00@\xdd\xa3WE\xb3\x0c'
2021-01-06 14:20:08,190 - root - DEBUG - 1102
2021-01-06 14:20:08,190 - root - DEBUG - 1102
2021-01-06 14:20:08,191 - root - DEBUG - b'\x00\x00\x00\x00\x00\x00\x00\x00'
2021-01-06 14:20:08,191 - root - DEBUG - b'\x00\x00\x00\x00\x00\x00\x00\x00'
Traceback (most recent call last):
  File "C:\Users\User\env\lib\site-packages\extract_msg\msg.py", line 422, in named
    return self.__namedProperties
AttributeError: 'Message' object has no attribute '_MSGFile__namedProperties'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\User\env\lib\site-packages\extract_msg\message.py", line 28, in __init__
    MessageBase.__init__(self, path, prefix, attachmentClass, filename, delayAttachments, overrideEncoding)
  File "C:\Users\User\env\lib\site-packages\extract_msg\message_base.py", line 61, in __init__
    self.named
  File "C:\Users\User\env\lib\site-packages\extract_msg\msg.py", line 424, in named
    self.__namedProperties = Named(self)
  File "C:\Users\User\env\lib\site-packages\extract_msg\named.py", line 63, in __init__
    self.__properties.append(StringNamedProperty(entry, names[entry['id']], msg._getTypedData(streamID)) if entry['pkind'] == constants.STRING_NAMED else NumericalNamedProperty(entry, msg._getTypedData(streamID)))
  File "C:\Users\User\env\lib\site-packages\extract_msg\msg.py", line 177, in _getTypedData
    found, result = self._getTypedStream('__substg1.0_' + id, prefix, _type)
  File "C:\Users\User\Documents\GitHub\sleuth\wwwsearch\parse_email\try_temp.py", line 56, in _getTypedStream
    return True, extract_msg.utils.parseType(int(_type, 16), contents, self.stringEncoding, extras)
  File "C:\Users\User\env\lib\site-packages\extract_msg\utils.py", line 459, in parseType
    lengths = tuple(struct.unpack('<i', stream[pos*8:(pos+1)*8]) for pos in range(len(stream) // 8))
  File "C:\Users\User\env\lib\site-packages\extract_msg\utils.py", line 459, in <genexpr>
    lengths = tuple(struct.unpack('<i', stream[pos*8:(pos+1)*8]) for pos in range(len(stream) // 8))
struct.error: unpack requires a buffer of 4 bytes
>>>

**Comment by TheElementalOfDestruction** [comment]
I've just published a new release (v0.27.16). Please upgrade to that version and run the code I provided once more.

**Comment by StephenGrey** [comment]
Will do

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by StephenGrey** [comment]
Looks like it is fixed now, thanks.
Returns:
2021-01-07 16:59:48,105 - root - DEBUG - 1102
2021-01-07 16:59:48,105 - root - DEBUG - b'\x00\x00\x00\x00\x00\x00\x00\x00'
2021-01-07 16:59:48,106 - extract_msg.utils - WARNING - Error while parsing multiple type. Expected length (0,), got 0. Ignoring.

But the body of the msg is parsed correctly.

(NB: that deals with vast majority of msgs that were failing. Only remaining issue is ones that throw:
"NotImplementedError: Current version of extract_msg does not support extraction of containers that are not embedded msg files." = But that looks like a known issue.

**Comment by TheElementalOfDestruction** [comment]
Lol, whoops. I made a small mistake in the code. While it won't actually affect anything other than a warning, it's not a good thing to have. That's why that warning is appearing: I forgot to unpack the value from the returned tuple. 

As for not implemented, yes that is the case that it is a known issue. It has to do with that being something that could take any format because it is application specific rather than file format specific.

**Comment by StephenGrey** [comment]
Great stuff - on that other issue,  as a work-around, if it is a case of weird attachments, why not just parse the text body but ignore the attachment with a warning. That way you'd still get something.

**Comment by TheElementalOfDestruction** [comment]
You actually can (Honestly, I need to write some actual documentation, but that would take a while and I am much better at writing code than I am at documenting it). There are 2 options (before 0.28.0 there was only 1) that allow you to do this. The first is `delayAttachments` which delays the parsing of attachments until you actively try to retrieve them. The second is `attachmentErrorBehavior` which was just added. With this option, you can specify how you want the class to deal with attachment errors. You currently have 3 options: Don't catch errors, catch `NotImplementedError`s, or catch all errors.

**Comment by StephenGrey** [comment]
Nice one - i'll give it a try. Am benchtesting various ways to extract data from about 100,000 messages.

**Comment by TheElementalOfDestruction** [comment]
If you don't care about any text in messages that are attached to the one you are parsing and only care about the body I would highly recommend setting that first option to true. It makes things a lot faster. 

I'm going to try around 0.29.0 to rewrite some of the underlying code to make it so things aren't just fully initialized right when it is first called. Many people don't actually use all of the data that is loaded, so waiting for some of it until needed is probably the smarted way to do things. Speed is currently a problem for this module.

**Comment by StephenGrey** [comment]
Yes - those options work well. I see you've actually documented most things pretty well in the actual codebase - i just had to actually read it !

**Comment by jasonxubin** [comment]
This thread is very helpful, I updated extract-msg to newest version and the issue disappeared! Thanks!
