### ISSUE TITLE
extract_msg error message "Error: Could not recognize msg class type "IPM.Message"."

### ISSUE THREAD

**Issue by frankl2code** [TeamMsgExtractor/msg-extractor#218]
I am using extract_msg in a Python script.
I am opening a .msg file.
extract_msg is at version 0.28.7
Python is version 3.9.6
I am running on Windows 10 Pro
I get this error on this command: "msg = extract_msg.openMsg(msgfile)"

[extract_msg_output.txt](https://github.com/TeamMsgExtractor/msg-extractor/files/7541587/extract_msg_output.txt)

**Comment by TheElementalOfDestruction** [comment]
So the error message is a little bit bad right now, but is being fixed in the next version, however it is actually correct in this instance: "IPM.Message" is not a recognized msg class type. It is not listed, at all, in Microsoft's documentation, however "IPM.*", which this would be the only thing left that could match, is simply a common type, with no specifications according to Microsoft.

If I might ask, what exactly generated that MSG file?

**Comment by frankl2code** [comment]
It is an email from 2014 from someone in charge of resources at a company I used to work for.

The email has an excel file attached.

The email was sent to a group email address that I can no longer open.

I think I can send it to you as long as you don’t contact any of the people in the email.

 

Frank Posa

(847) 732-5957

***@***.***

**Comment by TheElementalOfDestruction** [comment]
Appologies for the misunderstanding, I was trying to ask what program did you use to save the msg file itself (if it was not saved using outlook, that may explain the strange class type. If it *was* saved using Outlook, then Microsoft has some explaining to do).

Additionally, you can send it to arceusthe@gmail.com, as long as it is in a zip file first, as sometimes MSG files will get modified when attached directly. All messages sent to me will not be made public without express permission from the sender, and additionally any data inside of it will not be used for anything other than finding ways to improve the module.

**Comment by frankl2code** [comment]
I’m not sure how it was saved. There are several messages in the directory which was zipped and sent to me by a colleague. Some of them work just fine, until I ran into this one. I am no longer in contact with the person who sent it, so I can’t verify how these emails were saved to disk.

 

I will upload this one so you have something to work with.

 

Thanks for your help.

 

Frank Posa

(847) 732-5957

***@***.***

**Comment by TheElementalOfDestruction** [comment]
Only issue I can really see in my code is that the attachment code doesn't run for MSGFile and only MessageBase. Only problem with this is that attachments that also have a bad classtype will not be called with strict more off and so may cause errors that are harder to resolve. Anyways, I'll move that code around a bit, but aside from that, the problem is with the file itself.

I think I'll just close this issue, as there isn't really anything to be done about it directly.

**Comment by frankl2code** [comment]
If you’re interested, I was able to get around this error by using the win32com.client module.

 

So I added a “try” to my code -- so if the extract_msg module fails to open an email .msg file, I try to use win32com.client to open it. That worked. Even though the data that is retrieved is in a slightly different format, I get all of the email and the attachments.

 

Out of 18 emails in the directory I was attempting to convert to text, only one had this issue, but still my script was able to process all of them using this method.

 

I don’t particularly like my solution, so if you ever decide to try and get your code to work with that one email msg, please let me know.

 

Thanks,

 

Frank Posa

(847) 732-5957

***@***.***

**Comment by TheElementalOfDestruction** [comment]
Like I said, not an issue with the code (not one that isn't being fixed in 0.29.0 anyways related to the class types not properly being parsed). According to Microsoft specifications, what you have is a generic msg and not a Message, and assuming that it is a message could cause problems. If you are confident it is a message you can try to just open it directly with the Message class instead of the openMsg function, although that is discouraged. If you just want to open generic MSG files with openMsg you can also give it the option `strict = false` and that would return and instance of MSGFile.

Microsoft has the ability to reserve `IPM.Message` for anything they want in the future, so if they were to reserve it for something else then any versions of this module that assumed it was a Message would suddenly be broken.

Side note, I don't believe win32com would function properly on Linux or Mac, which this module is supposed to be compatible with.

**Comment by frankl2code** [comment]
Your last sentence is exactly why I didn’t want to use win32com. I don’t know about Mac (but you’re probably right), but I’m pretty sure I won’t even be able to install the module on Unix or Linux.

 

I believe I tried strict=false and it still failed. Given it was only one message out of 18, for now I’m assuming it is an anomaly, and I’m hoping to not see this issue in other message files.

 

I was thinking of opening the bad message file and then re-saving it to see what happens.

 

Thanks for responding.

 

Frank Posa

(847) 732-5957

***@***.***

**Comment by TheElementalOfDestruction** [comment]
The error you got was likely from trying to save, as the save function is not implemented for MSGFile, as there is no real standard defined for how it should look internally, or not one that is entirely clear. As such, saving isn't something really defined completely. Take contact files, for example. They aren't likely to have bodies or to and from, etc, so trying to save them from the base class wouldn't make sense.

Unless you can think of a way that makes sense with every type of file... well, there isn't much I can do for that one file, as it literally is not defined by the standards.

**Comment by frankl2code** [comment]
Thanks! I’ll let you know if I am able to repair that file some other way. Since the “to” was damaged in this file, that may have been caused by someone trying to save it.

 

Anyway, thanks again for responding. It’s good information for me.

 

Frank Posa

(847) 732-5957

***@***.***

**Comment by TheElementalOfDestruction** [comment]
It's also good to have someone ask questions that force me to make sure I'm not doing things in a stupid way, lol. Now I know what else needs to change in the next version.
